package entity;

// Generated 18-abr-2015 2:20:08 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditoria generated by hbm2java
 */
@Entity
@Table(name = "auditoria", schema = "public")
public class Auditoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 200458506252851566L;
	private int id;
	private String usuarioId;
	private char operacion;
	private String descripcion;
	private Date fechaAuditoria;
	private String tablaAuditoria;
	private String tablaId;

	public Auditoria() {
	}


	public Auditoria(int id, String usuarioId, char operacion,
			String descripcion, Date fechaAuditoria, String tablaAuditoria,
			String tablaId) {
		this.id = id;
		this.usuarioId = usuarioId;
		this.operacion = operacion;
		this.descripcion = descripcion;
		this.fechaAuditoria = fechaAuditoria;
		this.tablaAuditoria = tablaAuditoria;
		this.tablaId = tablaId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "usuario_id", nullable = false, length = 8)
	public String getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(String usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "operacion", nullable = false, length = 1)
	public char getOperacion() {
		return this.operacion;
	}

	public void setOperacion(char operacion) {
		this.operacion = operacion;
	}

	@Column(name = "descripcion", length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "fecha_auditoria", nullable = false, length = 21)
	public Date getFechaAuditoria() {
		return this.fechaAuditoria;
	}

	public void setFechaAuditoria(Date fechaAuditoria) {
		this.fechaAuditoria = fechaAuditoria;
	}

	@Column(name = "tabla_auditoria", length = 30)
	public String getTablaAuditoria() {
		return this.tablaAuditoria;
	}

	public void setTablaAuditoria(String tablaAuditoria) {
		this.tablaAuditoria = tablaAuditoria;
	}

	@Column(name = "tabla_id", nullable = false, length = 15)
	public String getTablaId() {
		return this.tablaId;
	}

	public void setTablaId(String tablaId) {
		this.tablaId = tablaId;
	}

}
