package entity;

// Generated 18-abr-2015 2:20:08 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PacienteId generated by hbm2java
 */
@Entity
@Table(name = "paciente", schema = "public")
public class Paciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6622479156066304645L;
	private Integer id;
	private int identificacion;
	private String nombresApellidos;
	private char estado;
	private String telefono;
	private String correo;
	private char progNutricion;
	private Integer idProyecto;

	public Paciente() {
	}

	public Paciente(int identificacion, String nombresApellidos, char estado,
			char progNutricion) {
		this.identificacion = identificacion;
		this.nombresApellidos = nombresApellidos;
		this.estado = estado;
		this.progNutricion = progNutricion;
	}

	public Paciente(Integer id, int identificacion, String nombresApellidos,
			char estado, String telefono, String correo, char progNutricion,
			Integer idProyecto) {
		this.id = id;
		this.identificacion = identificacion;
		this.nombresApellidos = nombresApellidos;
		this.estado = estado;
		this.telefono = telefono;
		this.correo = correo;
		this.progNutricion = progNutricion;
		this.idProyecto = idProyecto;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "identificacion", nullable = false)
	public int getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(int identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "nombres_apellidos", nullable = false, length = 100)
	public String getNombresApellidos() {
		return this.nombresApellidos;
	}

	public void setNombresApellidos(String nombresApellidos) {
		this.nombresApellidos = nombresApellidos;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "telefono", length = 30)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correo", length = 80)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "prog_nutricion", nullable = false, length = 1)
	public char getProgNutricion() {
		return this.progNutricion;
	}

	public void setProgNutricion(char progNutricion) {
		this.progNutricion = progNutricion;
	}

	@Column(name = "id_proyecto")
	public Integer getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Integer idProyecto) {
		this.idProyecto = idProyecto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Paciente))
			return false;
		Paciente castOther = (Paciente) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& (this.getIdentificacion() == castOther.getIdentificacion())
				&& ((this.getNombresApellidos() == castOther
						.getNombresApellidos()) || (this.getNombresApellidos() != null
						&& castOther.getNombresApellidos() != null && this
						.getNombresApellidos().equals(
								castOther.getNombresApellidos())))
				&& (this.getEstado() == castOther.getEstado())
				&& ((this.getTelefono() == castOther.getTelefono()) || (this
						.getTelefono() != null
						&& castOther.getTelefono() != null && this
						.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& (this.getProgNutricion() == castOther.getProgNutricion())
				&& ((this.getIdProyecto() == castOther.getIdProyecto()) || (this
						.getIdProyecto() != null
						&& castOther.getIdProyecto() != null && this
						.getIdProyecto().equals(castOther.getIdProyecto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + this.getIdentificacion();
		result = 37
				* result
				+ (getNombresApellidos() == null ? 0 : this
						.getNombresApellidos().hashCode());
		result = 37 * result + this.getEstado();
		result = 37 * result
				+ (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37 * result + this.getProgNutricion();
		result = 37
				* result
				+ (getIdProyecto() == null ? 0 : this.getIdProyecto()
						.hashCode());
		return result;
	}

}
