package entity;

// Generated 18-abr-2015 2:20:08 by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public")
public class Usuario {

	private int id;
	private String login;
	private String password;
	private String apellidosNombres;
	private Timestamp fechaCreacion;
	private char estado;
	private String correo;
	private Timestamp fechaClave;
	private char tipoUsuario;
	private Integer idProyecto;

	public Usuario() {
	}

	public Usuario(int id, String login, String password,
			String apellidosNombres, Timestamp fechaCreacion, char estado,
			Timestamp fechaClave) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.apellidosNombres = apellidosNombres;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.fechaClave = fechaClave;
	}

	public Usuario(int id, String login, String password,
			String apellidosNombres, Timestamp fechaCreacion, char estado,
			String correo, Timestamp fechaClave, char tipoUsuario,
			int idProyecto) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.apellidosNombres = apellidosNombres;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.correo = correo;
		this.fechaClave = fechaClave;
		this.tipoUsuario = tipoUsuario;
		this.idProyecto = idProyecto;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "login", nullable = false, length = 8)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "apellidos_nombres", nullable = false, length = 60)
	public String getApellidosNombres() {
		return this.apellidosNombres;
	}

	public void setApellidosNombres(String apellidosNombres) {
		this.apellidosNombres = apellidosNombres;
	}

	@Column(name = "fecha_creacion", nullable = false, length = 35)
	public Timestamp getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Timestamp fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "correo", length = 60)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "fecha_clave", nullable = false, length = 35)
	public Timestamp getFechaClave() {
		return this.fechaClave;
	}

	public void setFechaClave(Timestamp fechaClave) {
		this.fechaClave = fechaClave;
	}

	@Column(name = "tipo_usuario", length = 1)
	public Character getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(Character tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "id_proyecto")
	public Integer getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Integer idProyecto) {
		this.idProyecto = idProyecto;
	}

}
